import 'regenerator-runtime/runtime';
import wixRunMode from 'wix-run-mode';
import ejs from 'ejs';
import path from 'path';
import wixExpressCsrf from 'wix-express-csrf';
import wixExpressRequireHttps from 'wix-express-require-https';

module.exports = (app, context) => {
  const config = context.config.load('autogenerated-fullstack');
  const isProduction = wixRunMode.isProduction();

  app.use(wixExpressCsrf());
  app.use(wixExpressRequireHttps);

  app.get('/', context.hadron.middleware(), (req, res) => {
    const hadron = res.locals.hadron;
    const renderModel = getRenderModel(req, hadron);
    const templatePath = path.join(
      hadron.staticLocalPath('com.wixpress.autogenerated-fullstack', './src'),
      'index.ejs',
    );
    ejs.renderFile(
      templatePath,
      renderModel,
      {
        cache: isProduction,
        filename: templatePath,
      },
      (err, str) => res.send(str),
    );
  });

  function getRenderModel(req, hadron) {
    return {
      clientTopology: {
        staticsBaseUrl: hadron.staticUrl(
          'com.wixpress.autogenerated-fullstack',
          config.clientTopology.staticsBaseUrl,
        ),
      },
      locale: req.aspects['web-context'].language,
      basename: req.aspects['web-context'].basename,
      debug:
        req.aspects['web-context'].debug ||
        process.env.NODE_ENV === 'development',
      clientTopology: config.clientTopology,
      title: 'Wix Full Stack Project Boilerplate',
    };
  }

  return app;
};
