const path = require('path');
const bootstrap = require('wix-bootstrap-ng');
const greynode = require('wix-bootstrap-greynode');
const hadron = require('wix-bootstrap-hadron');

const rootDir = process.env.SRC_PATH || './dist/src';
const getPath = filename => path.join(rootDir, filename);

// list the artifacts you want hadron to manage for you
const hadronOpts = {
  staticArtifacts: [
    {
      artifactId: 'com.wixpress.autogenerated-fullstack',
    },
  ],
};

bootstrap()
  .use(greynode)
  .use(hadron, hadronOpts)
  .express(getPath('server'))
  .start({ disableCluster: process.env.NODE_ENV === 'development' });
